language: go
sudo: false
go:
  - 1.6
before_install:
  - sed -i -e "s,_ \"github.com/mattn/go-oci8\",,g" src/web/server.go
  - sed -i -e "s,_ \"gopkg.in/rana/ora.v3\",,g" src/web/server.go
install:
  - go get github.com/vkuznet/cmsauth
  - go get github.com/vkuznet/x509proxy
  - go get github.com/go-sql-driver/mysql
  - go get github.com/mattn/go-sqlite3
    #  - go get github.com/mattn/go-oci8
    #  - go get gopkg.in/rana/ora.v3"
